# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_couresorg_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='couresorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
