# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userask',
            old_name='coures',
            new_name='couser_name',
        ),
    ]
