# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20190311_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userask',
            old_name='couser_name',
            new_name='course_name',
        ),
    ]
