# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190312_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='coures',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='课程标签'),
        ),
        migrations.AddField(
            model_name='coures',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='老师告诉你'),
        ),
        migrations.AddField(
            model_name='coures',
            name='youneed_know',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
    ]
