# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190314_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='coures',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
