# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190304_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('mele', '男'), ('female', '女')], default='female', max_length=6),
        ),
    ]
